spring.datasource.url=jdbc:postgresql://localhost:5432/tax-calculation
spring.datasource.username=amandasantos
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true

logging.level.org.springframework.batch=DEBUG